
export default {
    // urlRegister : 'https://pizzadel-app.herokuapp.com/api/auth/register',
    // urlLogin : 'https://pizzadel-app.herokuapp.com/api/auth/login',
    // urlGetUserInfo: 'https://pizzadel-app.herokuapp.com/api/auth/getdata',
    // urlPaymentOrder: 'https://pizzadel-app.herokuapp.com/api/auth/payment/orders',
    // urlPaymentOrderSuccess: 'https://pizzadel-app.herokuapp.com/api/auth/payment/orders/success',
    // urlPaymentOrderStore: 'https://pizzadel-app.herokuapp.com/api/auth/payment/storeorder',
    // urlVerifyUser: 'https://pizzadel-app.herokuapp.com/api/auth/verify',
    // urlUpdatePass:'https://pizzadel-app.herokuapp.com/api/auth/updatepassword',
    // urlGetOrder: 'https://pizzadel-app.herokuapp.com/api/auth/getorder',
    // urlUpdateOrder: 'https://pizzadel-app.herokuapp.com/api/auth/updateorder',
    urlRegister : 'http://localhost:3333/api/auth/register',
    urlLogin : 'http://localhost:3333/api/auth/login',
    urlGetUserInfo: 'http://localhost:3333/api/auth/getdata',
    urlPaymentOrder: 'http://localhost:3333/api/auth/payment/orders',
    urlPaymentOrderSuccess: 'http://localhost:3333/api/auth/payment/orders/success',
    urlPaymentOrderStore: 'http://localhost:3333/api/auth/payment/storeorder',
    urlVerifyUser: 'http://localhost:3333/api/auth/verify',
    urlUpdatePass:'http://localhost:3333/api/auth/updatepassword',
    urlGetOrder: 'http://localhost:3333/api/auth/getorder',
    urlUpdateOrder: 'http://localhost:3333/api/auth/updateorder',
    urlGetInv: 'http://localhost:3333/api/auth/inventory',

};
